---
- name: Disable direct SSH root login on all app servers
  hosts: app_servers
  become: true

  tasks:
    - name: Ensure PermitRootLogin is set to no
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
        backup: yes

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted
