---
- name: Ensure Apache is up on all app servers
  hosts: nautlius_app_servers
  become: yes
  vars:
    apache_port: 5003
    apache_package:
      RedHat: httpd
      Debian: apache2

  tasks:
    - name: Install Apache
      package:
        name: "{{ apache_package[ansible_os_family] }}"
        state: present
      register: apache_install

    - name: Show installation message
      debug:
        msg: "Apache was installed or already present on {{ inventory_hostname }}"
      when: apache_install.changed or apache_install is defined

    - name: Ensure Apache is running
      service:
        name: "{{ apache_package[ansible_os_family] }}"
        state: started
        enabled: yes
      register: apache_service

    - name: Show service status
      debug:
        msg: "Apache is running on {{ inventory_hostname }}"
      when: apache_service.changed or apache_service is defined

    - name: Configure Apache to listen on port {{ apache_port }}
      lineinfile:
        path: "{{ '/etc/httpd/conf/httpd.conf' if ansible_os_family == 'RedHat' else '/etc/apache2/ports.conf' }}"
        regexp: '^Listen '
        line: "Listen {{ apache_port }}"
        state: present
        backup: yes
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: "{{ apache_package[ansible_os_family] }}"
        state: restarted
      listen: Restart Apache
      register: apache_restart

    - name: Show restart message
      debug:
        msg: "Apache was restarted on {{ inventory_hostname }}"
      when: apache_restart is changed
